{% set name = "mpbn" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colomoto_jupyter >=0.8.0
    - clingo >=5.4

test:
    imports:
        - mpbn

about:
  home: https://github.com/pauleve/mpbn
  summary: 'Simple implementation of Most Permissive semantics of Boolean networks'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C

