{% set name = "mpbn" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

channels:
  - colomoto
  - potassco

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colomoto_jupyter
    - clingo

about:
  home: https://github.com/pauleve/mpbn
  summary: 'Simple implementation of Most Permissive semantics of Boolean networks'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C

