mp_state(default,0,1,-1).
mp_state(default,0,2,-1).
mp_state(default,0,3,-1).
mp_state(default,1,1,1).
mp_state(default,1,2,1).
mp_state(default,1,3,1).
timepoint(default,0).
timepoint(default,1).
is_reachable(default,0,1).
